### ISSUE TITLE
Error : make OPTION=profiler  : undefined reference to 'cupti...'

### ISSUE THREAD

**Issue by beckdav** [NVlabs/sassifi#2]
Hi, 
I am trying to get sassifi up and running on my Ubuntu 12.04 machine with CUDA 7.0 but currently cannot successfully profile the example simple_add provded. 
I believe I have followed all steps outlined in the user guide and am setting all required environments as per my setup as follows:
    
    export SASSIFI_HOME=/home/ssc-obdh/Documents/sassifi-master
    export SASSI_SRC=/home/ssc-obdh/Documents/SASSI-master
    export INST_LIB_DIR=$SASSI_SRC/instlibs/lib/
    export CCDIR=/usr/lib/gcc/x86_64-linuc-gnu/4.9.4/
    export CUDA_BASE_DIR=/usr/local/sassi7
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CUDA_BASE_DIR/lib64/:$CUDA_BASE_DIR/extras/CUPTI/lib64/
    export PATH=$CUDA_BASE_DIR/bin/:$PATH
 
... but I am getting the following error, any help would be greatly appreciated, I also get the same error when using the test.sh script in top level. 

    ssc-obdh@ssc-obdh-OptiPlex-790:~/Documents/sassifi-master/suites/example/simple_add$ make OPTION=profiler
    rm -f *.o *~ simple_add
    nvcc  -o simple_add simple_add.cu -O3 -g -rdc=true -Xptxas -v -I/usr/local/sassi7/include/ -Xptxas --sassi-inst-before="all" -Xptxas --sassi-before-args="reg-info\,mem-info" -L/usr/local/sassi7/lib64 -std=c++11 -g -gencode arch=compute_50,code=sm_50  -lcudart -lcudadevrt -lm -L/usr/local/sassi7/extras/CUPTI/lib64 -lcupti  -L/home/ssc-obdh/Documents/SASSI-master/instlibs/lib/ -lprofiler
    ******************************************************************************
    *
    *                       SASSI Instrumentation Details
    *
    *  For the settings you passed in, you'll need to make sure that you have
    *  an instrumentation library with the following properties:
    *  - It MUST BE compiled using only 16 registers!! To accomplish this
    *    simply compile your library with the nvcc flag, --maxrregcount=16
    *  - It must define the following functions:
    *      __device__ void     sassi_before_handler(SASSIBeforeParams*,SASSIMemoryParams*,SASSIRegisterParams*)
    *
    ******************************************************************************
    ptxas info    : 1103 bytes gmem
    ptxas info    : Function properties for cudaMalloc
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Function properties for cudaFuncGetAttributes
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Function properties for cudaDeviceGetAttribute
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Function properties for cudaGetDevice
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Function properties for cudaOccupancyMaxActiveBlocksPerMultiprocessor
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Function properties for cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Compiling entry function '_Z10simple_addi' for 'sm_50'
    ptxas info    : Function properties for _Z10simple_addi
    240 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Used 10 registers, 324 bytes cmem[0]
    /home/ssc-obdh/Documents/SASSI-master/instlibs/lib//libprofiler.a(profiler.o): In function `sassi::lazy_allocator::lazy_allocator(void (*)(), void (*)(sassi::lazy_allocator::device_reset_reason), void (*)(CUpti_CallbackData const*), void (*)(CUpti_CallbackData const*))':
    tmpxft_00003acb_00000000-4_profiler.cudafe1.cpp:    (.text._ZN5sassi14lazy_allocatorC2EPFvvEPFvNS0_19device_reset_reasonEEPFvPK18CUpti_CallbackDataESA_[_ZN5sassi14lazy_allocatorC5EPFvvEPFvNS0_19device_reset_reasonEEPFvPK18CUpti_CallbackDataESA_]+0x25): undefined reference to `cuptiSubscribe'
    tmpxft_00003acb_00000000-4_profiler.cudafe1.cpp:(.text._ZN5sassi14lazy_allocatorC2EPFvvEPFvNS0_19device_reset_reasonEEPFvPK18CUpti_CallbackDataESA_[_ZN5sassi14lazy_allocatorC5EPFvvEPFvNS0_19device_reset_reasonEEPFvPK18CUpti_CallbackDataESA_]+0x47): undefined reference to `cuptiEnableCallback'
    tmpxft_00003acb_00000000-4_profiler.cudafe1.cpp:    (.text._ZN5sassi14lazy_allocatorC2EPFvvEPFvNS0_19device_reset_reasonEEPFvPK18CUpti_CallbackDataESA_[_ZN5sassi14lazy_allocatorC5EPFvvEPFvNS0_19device_reset_reasonEEPFvPK18CUpti_CallbackDataESA_]+0x172): undefined reference to `cuptiGetResultString'
    ... etc ... 
    collect2: error: ld returned 1 exit status
    make: *** [simple_add] Error 1

**Comment by sivahari** [comment]
Looks like it is not able to find CUPTI functions. I noted that you used "-L/usr/local/sassi7/extras/CUPTI/lib64 -lcupti", which should tell the compiler where to find CUPTI. Ensure that /usr/local/sassi7/extras/CUPTI/lib64 path exists in your system.
Another thing to try would be to compile and run a SASSI handler to ensure that SASSI is setup correctly and you can compile applications using other handlers (e.g., ophist in  https://github.com/NVlabs/SASSI/blob/master/example/Makefile).

**Comment by beckdav** [comment]
Thanks for the quick reply! 

I can confirm the CUPTI lib directory and contents exists: 

    ssc-obdh@ssc-obdh-OptiPlex-790:/usr/local/sassi7/extras/CUPTI/lib64$ ls
    libcupti.so  libcupti.so.7.0  libcupti.so.7.0.28

I can confirm that trying to compile and run the SASSI example also gives me an error
Looks like I probably made a silly error when setting up SASSI, I will try and retrace my steps to find where I went wrong, thanks for your help so far! 

    ssc-obdh@ssc-obdh-OptiPlex-790:~/Documents/SASSI-master/example$ make
    /usr/local/sassi7/bin/nvcc -o matrixMul matrixMul.o -gencode arch=compute_50,code=sm_50 -Xlinker "--wrap=main" -Xlinker "--wrap=exit" -L../instlibs/lib -lbranch -L/usr/local/sassi7/extras/CUPTI/lib64 -lcupti  -lcudadevrt -Xlinker -rpath,/usr/local/sassi7/extras/CUPTI/lib64 -L/lib -lboost_regex -lcrypto -Xlinker -rpath,/lib
    nvlink error   : Undefined reference to '_Z20sassi_before_handlerP17SASSIBeforeParamsP21SASSICondBranchParams' in 'matrixMul.o'
    make: *** [matrixMul] Error 255

**Comment by beckdav** [comment]
Hi, 
I have reinstalled SASSI (wasnt correctly installed due to error in boost version) and am now able to compile and use other SASSI example handlers. 

However I am still getting the following error trying to make the example for profiling, 

I am 99% sure I have all environment variables correctly setup ... Do you think I still have an issue in the setup of my SASSI install? - Any thoughts or tips greatly welcomed ... 

    ssc-obdh@ssc-obdh-OptiPlex-790:~/Documents/sassifi-master/suites/example/simple_add$ make OPTION=profiler
    rm -f *.o *~ simple_add

    /usr/local/sassi7/bin/nvcc -o simple_add simple_add.cu -O3 -g -rdc=true -Xptxas -v -I/usr/local/sassi7/include/ -Xptxas --sassi-inst-before="all" -Xptxas --sassi-before-args="reg-info\,mem-info" -L/usr/local/sassi7/lib64 -std=c++11 -g -gencode arch=compute_50,code=sm_50 -lcudart -lcudadevrt -lm -LASSI_SRC/instlibs/lib -lprofiler -L/usr/local/sassi7/extras/CUPTI/lib64 -L/usr/local/sassi7/extras/CUPTI/include -lcupti 
    ******************************************************************************
    *
    *                       SASSI Instrumentation Details
    *
    *  For the settings you passed in, you'll need to make sure that you have
    *  an instrumentation library with the following properties:
    *  - It MUST BE compiled using only 16 registers!! To accomplish this
    *    simply compile your library with the nvcc flag, --maxrregcount=16
    *  - It must define the following functions:
    *      __device__ void     sassi_before_handler(SASSIBeforeParams*,SASSIMemoryParams*,SASSIRegisterParams*)
    *
    ******************************************************************************
    ptxas info    : 1103 bytes gmem
    ptxas info    : Function properties for cudaMalloc
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Function properties for cudaFuncGetAttributes
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Function properties for cudaDeviceGetAttribute
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Function properties for cudaGetDevice
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Function properties for cudaOccupancyMaxActiveBlocksPerMultiprocessor
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Function properties for cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Compiling entry function '_Z10simple_addi' for 'sm_50'
    ptxas info    : Function properties for _Z10simple_addi
    240 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Used 10 registers, 324 bytes cmem[0]
    nvlink error   : Undefined reference to '_Z20sassi_before_handlerP17SASSIBeforeParamsP17SASSIMemoryParamsP19SASSIRegisterParams' in '/tmp/tmpxft_000029db_00000000-17_simple_add.o'
    make: *** [simple_add] Error 255

**Comment by beckdav** [comment]
Hi, I have just completed a fresh install of SASSI and SASSIFI and have found managed to fix the issue i was having! 

I was actually experiencing an issue with the makefile for the example and the linking of CUPTI in the EXTRA_LINK_FLAGS section. 

Originally the EXTRA_LINK_FLAGS only contained $(CUPTI) with the addition of the -lcupti flag I was able to get the example to profile and perform error injection my modified EXTRA_LINK_FLAGS are shown below:

    ifeq (${OPTION},profiler)
    EXTRA_NVCC_FLAGS = $(BEFORE_ALL) $(BEFORE_REG_MEM_INFO)
    EXTRA_LINK_FLAGS = -L$(INST_LIB_DIR) -lprofiler $(CUPTI) -lcupti
    endif

    ifeq (${OPTION},inst_value_injector)
    EXTRA_NVCC_FLAGS = $(AFTER_REG_MEM) $(AFTER_REG_MEM_INFO) $(BRANCH_AROUND) 
    EXTRA_LINK_FLAGS = -L$(INST_LIB_DIR) -linstvalueinjector $(CUPTI) -lcupti
    endif

    ifeq (${OPTION},inst_address_injector)
    EXTRA_NVCC_FLAGS = $(AFTER_REG_MEM) $(AFTER_REG_MEM_INFO) $(BRANCH_AROUND) $(BEFORE_REG_MEM) $(BEFORE_REG_MEM_INFO)
    EXTRA_LINK_FLAGS = -L$(INST_LIB_DIR) -linstaddressinjector $(CUPTI) -lcupti
    endif
 
    ifeq (${OPTION},rf_injector)
    EXTRA_NVCC_FLAGS = $(BEFORE_ALL) $(BEFORE_REG_MEM_INFO) 
    EXTRA_LINK_FLAGS = -L$(INST_LIB_DIR) -lrfinjector $(CUPTI) -lcupti
    endif

**Comment by sivahari** [comment]
Great! Thanks for resolving the issue and reporting it here!

I thought `CUPTI` was defined as `-L$(CUPTI_LIB_DIR) -lcupti` in the [Makefile](https://github.com/NVlabs/sassifi/blob/master/suites/example/simple_add/Makefile#L14). It is possible that the order was important in your case.

Thanks,
Siva

**Comment by beckdav** [comment]
Hi Siva, 
No problem thanks for the code, detailed docs and help! 
You are right CUPTI is defined as correctly towards the top of the makefile so it wasn't actually the addition of -lcupti in the EXTRA_LINK_FLAGS I can confirm the fix on my system was actually the ordering of linking.
For me it will throw errors unless  CUPTI is linked last. 

Many Thanks, 
Becky.
