### ISSUE TITLE
Scheduler Injection

### ISSUE THREAD

**Issue by cpbridges** [NVlabs/sassifi#3]
Hi Folks,
Good work here! Do you have any way of injecting errors into the warp or block schedulers?
Chris

**Comment by sivahari** [comment]
Hi Chris,

SASSIFI can inject errors only in the ISA visible state. I don't think there is a direct way to inject those errors. If we know how such errors manifest at the architecture-level, SASSIFI can be used to study the impact of such manifestations at the program level. It is an interesting topic, but we have not looked into it.

Thanks,
Siva
