### ISSUE TITLE
SASSIFI

### ISSUE THREAD

**Issue by yuehs1994** [NVlabs/sassifi#7]
Hi Dr. Hari,
Thanks for your help. I modified some makefiles as you suggested, and benchmarks with only one source file (.cu file) worked in this way. However, all benchmarks with multiple source files failed.
 
Here is how I modified the makefile of k-means (from Rodinia version 3.1)
 
$(TARGET): cluster.o getopt.o kmeans.o kmeans_clustering.o kmeans_cuda.o rmse.o
       $(CC) $(CC_FLAGS) cluster.o getopt.o kmeans.o kmeans_clustering.o kmeans_cuda.o rmse.o -o kmeans - L/usr/local/cuda/lib64 -lcuda -lcudart -lm
 
%.o: %.[ch]
       $(CC) $(CC_FLAGS) $< -c
 
kmeans_cuda.o: kmeans_cuda.cu
       $(NVCC) -c kmeans_cuda.cu $(NVCC_FLAGS) -L$(CUDA_LIB_DIR)       $(LINK_FLAGS).
 It failed with “make OPTION=profiler/rf injector/...” command with the following error:
ptxas error : Undefined reference to '_Z20sassi_before_handlerP17SASSIBeforeParamsP17SASSIMemoryParamsP19SASSIRegisterParams' in ''
ptxas info : 2455 bytes gmem, 4352 bytes cmem[3]
ptxas info : Compiling entry function '_Z14invert_mappingPfS_ii' for 'sm_50'
ptxas info : Function properties for _Z14invert_mappingPfS_ii
240 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info : Used 14 registers, 344 bytes cmem[0]
ptxas info : Compiling entry function 'Z11kmeansPointPfiiiPiS_S_S0' for 'sm_50'
ptxas info : Function properties for Z11kmeansPointPfiiiPiS_S_S0
256 bytes stack frame, 12 bytes spill stores, 8 bytes spill loads
ptxas info : Used 16 registers, 380 bytes cmem[0], 1 textures
make: *** [kmeans_cuda.o] Error 255
BTW, I can compile it using the default "make" option after this modification. So I think the error is caused by the fault injection part.
Do you know how to solve this error?
I also sent you an e-mail.which have my makefile.
Thanks

**Comment by sivahari** [comment]
Adding $(EXTRA_LINK_FLAGS) to the final step and using $(NVCC) instead of $(CC) should help.

$(TARGET): cluster.o getopt.o kmeans.o kmeans_clustering.o kmeans_cuda.o rmse.o
$(NVCC) $(CC_FLAGS) cluster.o getopt.o kmeans.o kmeans_clustering.o kmeans_cuda.o rmse.o -o kmeans - L/usr/local/cuda/lib64 -lcuda -lcudart -lm $(EXTRA_LINK_FLAGS)

Let me know if this doesn't fix the issue. 

Siva
