### ISSUE TITLE
Issues in running SASSIFI

### ISSUE THREAD

**Issue by kakulo** [NVlabs/sassifi#8]
Hi,

I am trying to use SASSIFI to do fault injection to GPU programs. But when I try to run the demo by following the instructions there are some problems coming out. 

1)  “export
 INST_LIB_DIR=$SASSI_SRC/instlibs/lib/”
 seems wrong that I didn’t find this directory in SASSI Source directory. 
2) When the process reaches Step 4, which does
“cd suites/example/simple_add/ 
make 2 > stderr.txt make golden”
   I get this result,

azguolu@n01:~/download/sassifi/suites/example/simple_add$ cat golden_stderr.txt 
Segmentation fault (core dumped)

azguolu@n01:~/download/sassifi/suites/example/simple_add$ cat golden_stdout.txt 
Device 0 () is being used
memory: 4.0000 GB ECC off 32766 SMs x0
#CTAs=10, nreps=10, threads/CTA=1024

azguolu@n01:~/download/sassifi/suites/example/simple_add$ cat stderr.txt 
ptxas info    : 8 bytes gmem
ptxas info    : Function properties for cudaMalloc
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Function properties for cudaFuncGetAttributes
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Function properties for cudaDeviceGetAttribute
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Function properties for cudaGetDevice
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Function properties for cudaOccupancyMaxActiveBlocksPerMultiprocessor
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Function properties for cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Compiling entry function '_Z10simple_addi' for 'sm_37'
ptxas info    : Function properties for _Z10simple_addi
    96 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 6 registers, 324 bytes cmem[0]

azguolu@n01:~/download/sassifi/suites/example/simple_add$ ./simple_add 
Device 0 () is being used
memory: 4.0000 GB ECC off 32767 SMs x0
#CTAs=10, nreps=10, threads/CTA=1024
Segmentation fault (core dumped)

3) In Step 5, which does “make
 OPTION=profiler”, I get this bug,

azguolu@n01:~/download/sassifi/suites/example/simple_add$ make OPTION=profiler
rm -f *.o *~ simple_add
/opt/pasa_lib/sassi/bin/nvcc -o simple_add simple_add.cu -O3 -g -rdc=true -Xptxas -v -I/opt/pasa_lib/sassi/include/ -Xptxas --sassi-inst-before="all" -Xptxas --sassi-before-args="reg-info\,mem-info" -L/opt/pasa_lib/sassi/lib64 -std=c++11 -g -gencode arch=compute_37,code=sm_37  -lcudart -lcudadevrt -lm -L/opt/pasa_lib/sassi/extras/CUPTI/lib64 -lcupti  -L/opt/pasa_lib/sassi/lib64 -lprofiler
******************************************************************************
*
*                       SASSI Instrumentation Details
*
*  For the settings you passed in, you'll need to make sure that you have
*  an instrumentation library with the following properties:
*  - It MUST BE compiled using only 16 registers!! To accomplish this
*    simply compile your library with the nvcc flag, --maxrregcount=16
*  - It must define the following functions:
*      __device__ void sassi_before_handler(SASSIBeforeParams*,SASSIMemoryParams*,SASSIRegisterParams*)
*
******************************************************************************
ptxas info    : 1171 bytes gmem
ptxas info    : Function properties for cudaMalloc
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Function properties for cudaFuncGetAttributes
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Function properties for cudaDeviceGetAttribute
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Function properties for cudaGetDevice
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Function properties for cudaOccupancyMaxActiveBlocksPerMultiprocessor
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Function properties for cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Compiling entry function '_Z10simple_addi' for 'sm_37'
ptxas info    : Function properties for _Z10simple_addi
    240 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 10 registers, 324 bytes cmem[0]
nvlink error   : Undefined reference to '_Z20sassi_before_handlerP17SASSIBeforeParamsP17SASSIMemoryParamsP19SASSIRegisterParams' in '/tmp/tmpxft_000077d6_00000000-17_simple_add.o'
make: *** [simple_add] Error 255

Could you please help me figure these problems out? I appreciate it. 

Regards,

**Comment by sivahari** [comment]
Regarding the first comment above, $SASSI_SRC/instlibs/lib/ should be created when you compile the libraries using the makefiles provided by SASSI. Please look at these two lines https://github.com/NVlabs/SASSI/blob/master/instlibs/Makefile#L19 and https://github.com/NVlabs/SASSI/blob/master/instlibs/src/Makefile#L38. You may also want to review steps 2 and 3 listed [here](https://github.com/NVlabs/sassifi#setting-up-and-running-sassifi).

Can you please ensure that the GPU you are is supported by SASSI/SASSIFI? It's not clear from the stdout ("Device 0 () is being used"). SASSI and SASSIFI are supported only with CUDA-7 and for Fermi, Kepler, and Maxwell GPUs. Please see the prerequisites [here ](https://github.com/NVlabs/SASSI#prerequisites)and [here](https://github.com/NVlabs/sassifi#prerequisites).

It looks like the last concern (mentioned above) is related to the first issue. The linker wasn't able to find sassi_before_handler, which should be part of the library. It appears that the library directory is missing in the setup. Resolving that might also resolve this issue.

**Comment by kakulo** [comment]
Hi Dr. Hari,

Thanks for your response. 

The first issue and the 2nd issue is solved, but the last issue is still pending.
I am using P100 and CUDA-8 because the current system I am using cannot have CUDA-7 supported. I will try SASSIFI to the other systems once I get access to them. 

Here is the bug information for now.

Step 5: Profile the applicationrm -f *.o *~ simple_add
nvcc -o simple_add simple_add.cu -O3 -g -rdc=true -Xptxas -v -I/g/g90/guo7/guo-libs/sassi/include/ -Xptxas --sassi-inst-before="all" -Xptxas --sassi-before-args="reg-info\,mem-info" -L/g/g90/guo7/guo-libs/sassi/lib64 -std=c++11 -g -gencode arch=compute_60,code=sm_60  -lcudart -lcudadevrt -lm -L/g/g90/guo7/guo-libs/sassi/extras/CUPTI/lib64 -lcupti  -L/g/g90/guo7/guo-libs/SASSI_SRC/instlibs/lib/ -lprofiler
Set TMPDIR to /var/tmp/guo7 to workaround name conflicts
nvidia-wrapper executing after fixup:
+ exec /usr/tce/packages/cuda/cuda-8.0/nvidia/bin/nvcc -o simple_add simple_add.cu -O3 -g -rdc=true -Xptxas -v -I/g/g90/guo7/guo-libs/sassi/include/ -Xptxas --sassi-inst-before=all -Xptxas '--sassi-before-args=reg-info\,mem-info' -L/g/g90/guo7/guo-libs/sassi/lib64 -std=c++11 -g -gencode arch=compute_60,code=sm_60 -lcudart -lcudadevrt -lm -L/g/g90/guo7/guo-libs/sassi/extras/CUPTI/lib64 -lcupti -L/g/g90/guo7/guo-libs/SASSI_SRC/instlibs/lib/ -lprofiler -Xcompiler '"-Wl,-rpath,/usr/tce/packages/cuda/cuda-8.0/nvidia/lib64:/usr/tce/packages/cuda/cuda-8.0/syslib64"'
ptxas fatal   : Unknown option '-sassi-inst-before'
make: *** [Makefile:71: simple_add] Error 255

Thanks!

**Comment by sivahari** [comment]
Unfortunately, SASSI and SASSIFI do not work with CUDA-8 and/or Pascal-based GPUs. They only work with CUDA-7 and Fermi, Kepler, and Maxwell GPUs. ([Related thread](https://github.com/NVlabs/SASSI/issues/3).)

**Comment by kakulo** [comment]
Hi Dr. Hari,

I am using CUDA-7.0 on K40 now. But I still get this ptxas fault.

ice86@guo7:cat sassifi.err 
ptxas fatal   : Unknown option '-sassi-inst-before'
make: *** [simple_add] Error 255
ice86@guo7:cat sassifi.out 
Okay, inst_value

Step 1: Setting environment variables
Step 4.1: Collect golden stdout.txt and stderr.txt filesrm -f *.o *~ simple_add
nvcc -o simple_add simple_add.cu -O3 -g -rdc=true -Xptxas -v -I/g/g90/guo7/guo-libs/sassi7//include/  -L/g/g90/guo7/guo-libs/sassi7//lib64 -std=c++11 -g -gencode arch=compute_35,code=sm_35  -lcudart -lcudadevrt -lm 
mkdir -p /g/g90/guo7/guo-libs/sassifi/bin/none/example/
cp simple_add /g/g90/guo7/guo-libs/sassifi/bin/none/example/
./simple_add >golden_stdout.txt 2>golden_stderr.txt
Created the pickle file: /g/g90/guo7/guo-libs/sassifi/suites/example/simple_add/simple_add_kernel_regcount.p
Load it from the specific_params.py file

Step 5: Profile the applicationrm -f *.o *~ simple_add
nvcc -o simple_add simple_add.cu -O3 -g -rdc=true -Xptxas -v -I/g/g90/guo7/guo-libs/sassi7//include/ -Xptxas --sassi-inst-before="all" -Xptxas --sassi-before-args="reg-info\,mem-info" -L/g/g90/guo7/guo-libs/sassi7//lib64 -std=c++11 -g -gencode arch=compute_35,code=sm_35  -lcudart -lcudadevrt -lm -L/g/g90/guo7/guo-libs/sassi7//extras/CUPTI/lib64 -lcupti  -L/g/g90/guo7/guo-libs/SASSI_SRC/instlibs/lib/ -lprofiler

Thanks,

**Comment by sivahari** [comment]
Please ensure that you are using nvcc from sassi7/bin/.

**Comment by kakulo** [comment]
Hi Dr. Hari,

I am getting this error when running sassifi to lulesh.

ptxas info    : Function properties for _ZN6thrust6detail18contiguous_storageIiSaIiEED2Ev
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Function properties for _ZN6thrust6detail10functional5actorINS1_8argumentILj0EEEEC2Ev
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads                       
ptxas info    : Function properties for _ZN6thrust6detail10functional5actorINS1_8argumentILj1EEEEC2Ev
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads                       
ptxas info    : Function properties for _ZN6thrust6detail10functional5actorINS1_8argumentILj2EEEEC2Ev
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Function properties for _ZN6thrust6detail10functional5actorINS1_8argumentILj3EEEEC2Ev
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads                       
ptxas info    : Function properties for _ZN6thrust6detail10functional5actorINS1_8argumentILj4EEEEC2Ev
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads                       
ptxas info    : Function properties for _ZN6thrust6detail10functional5actorINS1_8argumentILj5EEEEC2Ev
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Function properties for _ZN6thrust6detail10functional5actorINS1_8argumentILj6EEEEC2Ev
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads                       
ptxas info    : Function properties for _ZN6thrust6detail10functional5actorINS1_8argumentILj7EEEEC2Ev
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads                       
ptxas info    : Function properties for _ZN6thrust6detail10functional5actorINS1_8argumentILj8EEEEC2Ev
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Function properties for _ZN6thrust6detail10functional5actorINS1_8argumentILj9EEEEC2Ev
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads                       
Traceback (most recent call last):
  File "generate_injection_list.py", line 118, in <module>                               
    main()
  File "generate_injection_list.py", line 114, in main
    gen_lists(app, countList, inj_mode)                                                  
  File "generate_injection_list.py", line 78, in gen_lists
    write_injection_list_file(app, inj_mode, "rf", bfm, MAX_INJ, total_count, countList)
  File "generate_injection_list.py", line 57, in write_injection_list_file               
    inj_op_id_seed = sp.num_regs[app][inj_kname]*random.random() # register selection    
KeyError: '_Z30CalcVolumeForceForElems_kernelILb1EEvPKdS1_S1_S1_diiPKiS1_S1_10TextureObjIdES5_S5_S5_S5_S5_PdS6_S6_Pii'

Do you have any idea about this? 

Thanks
